### ISSUE TITLE
缺少文件么？

### ISSUE THREAD

**Issue by andyjhb** [comfyanonymous/ComfyUI_experiments#6]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CLIPSeg module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CLIPSeg\\__init__.py'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\__init__.py", line 8, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\__init__.py", line 8, in <module>
    from .GMFSS_Fortuna_arch import Model as GMFSS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\GMFSS_Fortuna_arch.py", line 26, in <module>
    import cupy
ModuleNotFoundError: No module named 'cupy'

**Comment by ZhianLin** [comment]
在命令行执行pip install cupy来安装cupy库。
